import { AktePage } from "./AktePage"
import { HealthBuddyBox } from "./components/HealthBuddyBox"

export const routes = [
  { path: "/akte/*", element: <AktePage /> },
]

// Buddy-Widget-Slot: wird im rechten Buddy-Panel gerendert, bekommt onPrompt durch.
export const buddyWidgets = [HealthBuddyBox]

export const nav = [
  {
    path: "/akte",
    icon: "FolderHeart",
    labelKey: "akte",
    group: "overview",
    roles: [] as ("admin" | "user")[],
  },
]

export const i18n = {
  de: {
    akte: {
      title: "Meine Akte",
      page_title: "Meine Akte",
      page_subtitle: "Deine strukturierte Patientenakte",
      loading: "Laden…",
      nav: {
        section_akte: "Meine Akte",
        overview: "Übersicht",
        timeline: "Zeitstrahl",
        conditions: "Diagnosen",
        medications: "Medikamente",
        observations: "Laborwerte",
        allergies: "Allergien",
        events: "Ereignisse",
        imaging: "Bildgebung",
        practitioners: "Ärzte",
        documents: "Dokumente",
        notes: "Notizen",
        section_import: "Import",
        import: "eGA / FHIR",
        section_tracking: "Tracking",
        tracking: "Apple Health",
        sleep: "Schlaf",
      },
      tracking: { trend_title: "Verlauf", sleep_title: "Schlafverlauf" },
      loading_data: "Daten konnten nicht geladen werden.",
      period_days: "{{days}}T",
      import: {
        title: "Import",
        subtitle: "TK-eGA-Export oder FHIR-Bundle importieren. Importierte Daten sind read-only und bleiben von der eigenen Akte getrennt.",
        ega_button: "TK-eGA-ZIP",
        fhir_button: "FHIR-Bundle",
        importing: "Importiere…",
        failed: "Import fehlgeschlagen",
        result: "{{imported}} neu, {{updated}} aktualisiert",
        empty: "Noch nichts importiert.",
        empty_hint: "TK-Safe App öffnen → Akte exportieren → ZIP hier hochladen.",
        costs_title: "Kosten (Kassenleistungen)",
        cost_ambulant: "Arztbesuche abgerechnet",
        cost_medication: "Apothekenpreise gesamt",
        cost_copay: "Davon deine Zuzahlung",
        timeline_title: "Zeitstrahl",
        all: "Alle",
        records_empty: "Keine Einträge dieses Typs.",
        types: {
          Encounter: "Arztbesuche",
          AmbulantClaim: "Abrechnungen",
          MedicationDispense: "Medikamente",
          MedicationClaim: "Medikamentenabrechnung",
          HospitalStay: "Krankenhaus",
          Procedure: "Vorsorge",
          Condition: "Diagnosen",
        },
      },
      akte: {
        title: "Meine Patientenakte",
        edit: "Bearbeiten",
        cancel: "Abbrechen",
        save: "Speichern",
        saving: "Speichern…",
        create: "Akte anlegen",
        creating: "Wird angelegt…",
        new: "Neu",
        delete_confirm: "Eintrag wirklich löschen?",
        delete_title: "Löschen",
        edit_title: "Bearbeiten",
        verified_title: "Manuell verifiziert",
        unverified_title: "Nicht verifiziert — klicken zum Verifizieren",
        verify_title: "Zum Verifizieren klicken",
        close: "Schließen",
        no_entries: "Keine Einträge",
        empty_entries: "Noch keine Einträge vorhanden.",
        search_placeholder: "Suchen…",
        male: "♂ Männlich",
        female: "♀ Weiblich",
        diverse: "⚥ Divers",
        date: "Datum",
        error_boundary: "Akte-View Fehler",
      },
    },
  },
  en: {
    akte: {
      title: "My Record",
      page_title: "My Record",
      page_subtitle: "Your structured patient record",
      loading: "Loading…",
      nav: {
        section_akte: "My Record",
        overview: "Overview",
        timeline: "Timeline",
        conditions: "Diagnoses",
        medications: "Medications",
        observations: "Lab Values",
        allergies: "Allergies",
        events: "Events",
        imaging: "Imaging",
        practitioners: "Doctors",
        documents: "Documents",
        notes: "Notes",
        section_import: "Import",
        import: "eGA / FHIR",
        section_tracking: "Tracking",
        tracking: "Apple Health",
        sleep: "Sleep",
      },
      tracking: { trend_title: "Trends", sleep_title: "Sleep history" },
      loading_data: "Could not load data.",
      period_days: "{{days}}d",
      import: {
        title: "Import",
        subtitle: "Import a TK eGA export or a FHIR bundle. Imported data is read-only and kept separate from your own record.",
        ega_button: "TK eGA ZIP",
        fhir_button: "FHIR bundle",
        importing: "Importing…",
        failed: "Import failed",
        result: "{{imported}} new, {{updated}} updated",
        empty: "Nothing imported yet.",
        empty_hint: "Open the TK Safe app → export your record → upload the ZIP here.",
        costs_title: "Costs (statutory benefits)",
        cost_ambulant: "Outpatient visits billed",
        cost_medication: "Pharmacy prices total",
        cost_copay: "Of which your co-payment",
        timeline_title: "Timeline",
        all: "All",
        records_empty: "No entries of this type.",
        types: {
          Encounter: "Doctor visits",
          AmbulantClaim: "Claims",
          MedicationDispense: "Medications",
          MedicationClaim: "Medication claims",
          HospitalStay: "Hospital",
          Procedure: "Procedures",
          Condition: "Diagnoses",
        },
      },
      akte: {
        title: "My Patient Record",
        edit: "Edit",
        cancel: "Cancel",
        save: "Save",
        saving: "Saving…",
        create: "Create record",
        creating: "Creating…",
        new: "New",
        delete_confirm: "Really delete entry?",
        delete_title: "Delete",
        edit_title: "Edit",
        verified_title: "Manually verified",
        unverified_title: "Not verified — click to verify",
        verify_title: "Click to verify",
        close: "Close",
        no_entries: "No entries",
        empty_entries: "No entries yet.",
        search_placeholder: "Search…",
        male: "♂ Male",
        female: "♀ Female",
        diverse: "⚥ Diverse",
        date: "Date",
        error_boundary: "Record view error",
      },
    },
  },
}
