import { AktePage } from "./AktePage"

export const routes = [
  { path: "/akte/*", element: <AktePage /> },
]

export const nav = [
  {
    path: "/akte",
    icon: "FolderHeart",
    labelKey: "akte",
    group: "overview",
    roles: [] as ("admin" | "user")[],
  },
]

export const i18n = {
  de: {
    akte: {
      title: "Meine Akte",
      page_title: "Meine Akte",
      page_subtitle: "Deine strukturierte Patientenakte",
      loading: "Laden…",
      nav: {
        section_akte: "Meine Akte",
        overview: "Übersicht",
        timeline: "Zeitstrahl",
        conditions: "Diagnosen",
        medications: "Medikamente",
        observations: "Laborwerte",
        allergies: "Allergien",
        events: "Ereignisse",
        imaging: "Bildgebung",
        practitioners: "Ärzte",
        documents: "Dokumente",
        notes: "Notizen",
      },
      akte: {
        title: "Meine Patientenakte",
        edit: "Bearbeiten",
        cancel: "Abbrechen",
        save: "Speichern",
        saving: "Speichern…",
        create: "Akte anlegen",
        creating: "Wird angelegt…",
        new: "Neu",
        delete_confirm: "Eintrag wirklich löschen?",
        delete_title: "Löschen",
        edit_title: "Bearbeiten",
        verified_title: "Manuell verifiziert",
        unverified_title: "Nicht verifiziert — klicken zum Verifizieren",
        verify_title: "Zum Verifizieren klicken",
        close: "Schließen",
        no_entries: "Keine Einträge",
        empty_entries: "Noch keine Einträge vorhanden.",
        search_placeholder: "Suchen…",
        male: "♂ Männlich",
        female: "♀ Weiblich",
        diverse: "⚥ Divers",
        date: "Datum",
        error_boundary: "Akte-View Fehler",
      },
    },
  },
  en: {
    akte: {
      title: "My Record",
      page_title: "My Record",
      page_subtitle: "Your structured patient record",
      loading: "Loading…",
      nav: {
        section_akte: "My Record",
        overview: "Overview",
        timeline: "Timeline",
        conditions: "Diagnoses",
        medications: "Medications",
        observations: "Lab Values",
        allergies: "Allergies",
        events: "Events",
        imaging: "Imaging",
        practitioners: "Doctors",
        documents: "Documents",
        notes: "Notes",
      },
      akte: {
        title: "My Patient Record",
        edit: "Edit",
        cancel: "Cancel",
        save: "Save",
        saving: "Saving…",
        create: "Create record",
        creating: "Creating…",
        new: "New",
        delete_confirm: "Really delete entry?",
        delete_title: "Delete",
        edit_title: "Edit",
        verified_title: "Manually verified",
        unverified_title: "Not verified — click to verify",
        verify_title: "Click to verify",
        close: "Close",
        no_entries: "No entries",
        empty_entries: "No entries yet.",
        search_placeholder: "Search…",
        male: "♂ Male",
        female: "♀ Female",
        diverse: "⚥ Diverse",
        date: "Date",
        error_boundary: "Record view error",
      },
    },
  },
}
