import { readdirSync, statSync, writeFileSync, existsSync, mkdirSync } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const modulesDir = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "modules")
mkdirSync(modulesDir, { recursive: true })   // robust auf frischem Checkout
const out = join(modulesDir, "index.generated.ts")

const ids = readdirSync(modulesDir).filter((n) => {
  const p = join(modulesDir, n)
  return statSync(p).isDirectory() && existsSync(join(p, "index.tsx"))
})

const imports = ids.map((id, i) => `import * as m${i} from "./${id}"`).join("\n")
const routes = ids.map((_, i) => `...m${i}.routes`).join(", ")
const nav = ids.map((_, i) => `...m${i}.nav`).join(", ")
const i18n = ids.map((_, i) => `m${i}.i18n`).join(", ")
writeFileSync(out,
`// AUTO-GENERATED by scripts/gen-modules.mjs — do not edit.
${imports}
export const moduleRoutes = [${routes}]
export const moduleNav = [${nav}]
export const moduleI18n = [${i18n}]
`)
console.log(`[gen-modules] ${ids.length} Modul(e): ${ids.join(", ") || "(keine)"}`)
