import { readdirSync, statSync, writeFileSync, existsSync, readFileSync, mkdirSync } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"

// Scannt src/themes/<id>/theme.json und erzeugt index.generated.ts — analog
// gen-modules.mjs. Dropin: Theme-Ordner reinlegen → erscheint im Picker.
// resolveJsonModule ist AUS → Manifest-Werte werden direkt in TS eingebettet.
const themesDir = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "themes")
mkdirSync(themesDir, { recursive: true })
const out = join(themesDir, "index.generated.ts")

const ids = readdirSync(themesDir).filter((n) => {
  const p = join(themesDir, n)
  return statSync(p).isDirectory() && existsSync(join(p, "theme.json"))
})

const parts = []
const imports = []
const entries = []

ids.forEach((id, i) => {
  let manifest
  try {
    manifest = JSON.parse(readFileSync(join(themesDir, id, "theme.json"), "utf8"))
  } catch (e) {
    console.error(`[gen-themes] theme.json von "${id}" ungültig — übersprungen: ${e.message}`)
    return
  }

  const dir = join(themesDir, id)
  const hasLayout = existsSync(join(dir, "layout.tsx"))
  const hasCss = existsSync(join(dir, "theme.css"))
  const preview = ["preview.jpg", "preview.png", "preview.webp"].find((f) => existsSync(join(dir, f)))

  if (hasLayout) imports.push(`import _layout${i} from "./${id}/layout"`)
  if (hasCss) imports.push(`import _css${i} from "./${id}/theme.css?raw"`)
  if (preview) imports.push(`import _prev${i} from "./${id}/${preview}?url"`)

  // Seiten-Templates: templates/<route>.html → { route: rohes HTML }.
  // Der Dateiname (ohne .html) ist der Routen-Schlüssel (z.B. buddy.html → "buddy").
  const tplDir = join(dir, "templates")
  const tplEntries = []
  if (existsSync(tplDir) && statSync(tplDir).isDirectory()) {
    for (const f of readdirSync(tplDir)) {
      if (!f.endsWith(".html")) continue
      const route = f.slice(0, -5)
      const varName = `_tpl${i}_${route.replace(/[^a-z0-9]/gi, "_")}`
      imports.push(`import ${varName} from "./${id}/templates/${f}?raw"`)
      tplEntries.push(`${JSON.stringify(route)}: ${varName}`)
    }
  }

  const fields = [
    `id: ${JSON.stringify(String(manifest.id ?? id))}`,
    `name: ${JSON.stringify(String(manifest.name ?? id))}`,
    `description: ${JSON.stringify(String(manifest.description ?? ""))}`,
    `author: ${JSON.stringify(manifest.author ? String(manifest.author) : "")}`,
    `version: ${JSON.stringify(manifest.version ? String(manifest.version) : "")}`,
    `layoutName: ${hasLayout ? "null" : JSON.stringify(manifest.layout ? String(manifest.layout) : "topnav")}`,
    `variables: ${JSON.stringify(manifest.variables && typeof manifest.variables === "object" ? manifest.variables : {})}`,
    hasLayout ? `customLayout: _layout${i}` : null,
    hasCss ? `css: _css${i}` : null,
    preview ? `preview: _prev${i}` : null,
    tplEntries.length ? `templates: { ${tplEntries.join(", ")} }` : null,
  ].filter(Boolean)

  entries.push(`  { ${fields.join(", ")} }`)
})

parts.push("// AUTO-GENERATED by scripts/gen-themes.mjs — do not edit.")
parts.push(`import type { GeneratedThemeEntry } from "@/shared/themes/types"`)
if (imports.length) parts.push(imports.join("\n"))
parts.push(`export const userThemes: GeneratedThemeEntry[] = [\n${entries.join(",\n")}\n]`)

writeFileSync(out, parts.join("\n") + "\n")
console.log(`[gen-themes] ${entries.length} Theme(s): ${ids.join(", ") || "(keine)"}`)
