import { readdirSync, statSync, writeFileSync, existsSync, mkdirSync, readFileSync } from "node:fs"
import { join, dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const modulesDir = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "modules")
mkdirSync(modulesDir, { recursive: true })   // robust auf frischem Checkout
const out = join(modulesDir, "index.generated.ts")

function hasMissingLocalImport(moduleDir) {
  const files = []
  const walk = (dir) => {
    for (const name of readdirSync(dir)) {
      const p = join(dir, name)
      if (statSync(p).isDirectory()) walk(p)
      else if (/\.(tsx?|mts|cts)$/.test(name)) files.push(p)
    }
  }
  walk(moduleDir)
  const importRe = /from\s+["'](\.\.[^"']+)["']/g
  for (const file of files) {
    const source = readFileSync(file, "utf8")
    for (const match of source.matchAll(importRe)) {
      const target = resolve(dirname(file), match[1])
      const candidates = [target, `${target}.ts`, `${target}.tsx`, join(target, "index.tsx")]
      if (!candidates.some((candidate) => existsSync(candidate))) return true
    }
  }
  return false
}

const ids = readdirSync(modulesDir).filter((n) => {
  const p = join(modulesDir, n)
  if (!statSync(p).isDirectory() || !existsSync(join(p, "index.tsx"))) return false
  if (hasMissingLocalImport(p)) {
    console.warn(`[gen-modules] überspringe ${n}: optionale Modulabhängigkeit fehlt`)
    return false
  }
  return true
})

const imports = ids.map((id, i) => `import * as m${i} from "./${id}"`).join("\n")
const mods = ids.map((_, i) => `m${i}`).join(", ")
const routes = ids.map((_, i) => `...m${i}.routes`).join(", ")
const nav = ids.map((_, i) => `...m${i}.nav`).join(", ")
const i18n = ids.map((_, i) => `m${i}.i18n`).join(", ")
writeFileSync(out,
`// AUTO-GENERATED by scripts/gen-modules.mjs — do not edit.
${imports}
// _opt breaks rolldown's static import-undefined analysis for optional exports.
function _opt<T>(mod: unknown, key: string): T[] {
  return ((mod as Record<string, unknown>)[key] as T[] | undefined) ?? []
}
const _mods: unknown[] = [${mods}]
export const moduleRoutes: unknown[] = [${routes}]
export const moduleNav: unknown[] = [${nav}]
export const moduleI18n: unknown[] = [${i18n}]
export const moduleBuddyWidgets: unknown[] = _mods.flatMap(m => _opt(m, "buddyWidgets"))
export const moduleWorkspaceTabs: unknown[] = _mods.flatMap(m => _opt(m, "workspaceTabs"))
export const moduleSlotBlocks: unknown[] = _mods.flatMap(m => _opt(m, "slotBlocks"))
export const moduleMediaSources: unknown[] = _mods.flatMap(m => _opt(m, "mediaSources"))
export const moduleMediaWorkflows: unknown[] = _mods.flatMap(m => _opt(m, "mediaWorkflows"))
`)
console.log(`[gen-modules] ${ids.length} Modul(e): ${ids.join(", ") || "(keine)"}`)
