import type { LlmProvider } from "./api"

export const KNOWN_PROVIDERS = [
  {
    id: "anthropic", name: "Anthropic", placeholder: "sk-ant-...",
    models: ["claude-sonnet-4-6", "claude-opus-4-7", "claude-haiku-4-5", "claude-sonnet-4-5", "claude-3-7-sonnet-20250219", "claude-3-5-haiku-20241022"],
  },
  {
    // LiteLLM-Routing: alle non-Anthropic/non-MiniMax Modelle MÜSSEN den Provider-Prefix haben.
    id: "openai", name: "OpenAI", placeholder: "sk-...",
    models: ["openai/gpt-4o", "openai/gpt-4o-mini", "openai/gpt-4-turbo", "openai/gpt-4", "openai/gpt-3.5-turbo", "openai/o1-preview", "openai/o1-mini"],
  },
  {
    // OAuth-Provider: ChatGPT Plus/Pro via Codex-Backend (chatgpt.com).
    // Kein API-Key — Login per OAuth, Token landet als oauth-Block in llm.json.
    id: "openai-codex", name: "ChatGPT Plus/Pro (Codex)", placeholder: "OAuth — kein Key nötig",
    auth: "oauth" as const,
    models: [
      "openai-codex/gpt-5.4",
      "openai-codex/gpt-5.3-codex",
      "openai-codex/gpt-5.3-codex-spark",
      "openai-codex/gpt-5.2",
      "openai-codex/gpt-5.2-codex",
      "openai-codex/gpt-5.1",
      "openai-codex/gpt-5.1-codex-max",
      "openai-codex/gpt-5.1-codex-mini",
    ],
  },
  {
    id: "openrouter", name: "OpenRouter", placeholder: "sk-or-...",
    models: ["openrouter/anthropic/claude-sonnet-4-6", "openrouter/openai/gpt-4o", "openrouter/google/gemini-2.0-flash-exp", "openrouter/deepseek/deepseek-r1", "openrouter/meta-llama/llama-3.3-70b-instruct"],
  },
  {
    id: "groq", name: "Groq", placeholder: "gsk_...",
    models: ["groq/llama-3.3-70b-versatile", "groq/llama-3.1-8b-instant", "groq/mixtral-8x7b-32768", "groq/deepseek-r1-distill-llama-70b"],
  },
  {
    id: "mistral", name: "Mistral", placeholder: "...",
    models: ["mistral/mistral-large-latest", "mistral/mistral-small-latest", "mistral/codestral-latest", "mistral/open-mistral-nemo"],
  },
  {
    id: "gemini", name: "Google Gemini", placeholder: "AIza...",
    models: ["gemini/gemini-2.0-flash-exp", "gemini/gemini-1.5-pro", "gemini/gemini-1.5-flash", "gemini/gemini-1.5-flash-8b"],
  },
  {
    id: "minimax", name: "MiniMax", placeholder: "eyJ...",
    models: ["MiniMax-M2", "MiniMax-M2.7", "abab6.5s-chat"],
  },
  {
    id: "nvidia", name: "NVIDIA NIM", placeholder: "nvapi-...",
    models: [
      "nvidia_nim/01-ai/yi-large",
      "nvidia_nim/abacusai/dracarys-llama-3.1-70b-instruct",
      "nvidia_nim/adept/fuyu-8b",
      "nvidia_nim/ai21labs/jamba-1.5-large-instruct",
      "nvidia_nim/aisingapore/sea-lion-7b-instruct",
      "nvidia_nim/baai/bge-m3",
      "nvidia_nim/bigcode/starcoder2-15b",
      "nvidia_nim/bytedance/seed-oss-36b-instruct",
      "nvidia_nim/databricks/dbrx-instruct",
      "nvidia_nim/deepseek-ai/deepseek-coder-6.7b-instruct",
      "nvidia_nim/deepseek-ai/deepseek-v4-flash",
      "nvidia_nim/deepseek-ai/deepseek-v4-pro",
      "nvidia_nim/google/codegemma-1.1-7b",
      "nvidia_nim/google/codegemma-7b",
      "nvidia_nim/google/deplot",
      "nvidia_nim/google/gemma-2-2b-it",
      "nvidia_nim/google/gemma-2b",
      "nvidia_nim/google/gemma-3-12b-it",
      "nvidia_nim/google/gemma-3-27b-it",
      "nvidia_nim/google/gemma-3-4b-it",
      "nvidia_nim/google/gemma-3n-e2b-it",
      "nvidia_nim/google/gemma-3n-e4b-it",
      "nvidia_nim/google/gemma-4-31b-it",
      "nvidia_nim/google/recurrentgemma-2b",
      "nvidia_nim/ibm/granite-3.0-3b-a800m-instruct",
      "nvidia_nim/ibm/granite-3.0-8b-instruct",
      "nvidia_nim/ibm/granite-34b-code-instruct",
      "nvidia_nim/ibm/granite-8b-code-instruct",
      "nvidia_nim/meta/codellama-70b",
      "nvidia_nim/meta/llama-3.1-405b-instruct",
      "nvidia_nim/meta/llama-3.1-70b-instruct",
      "nvidia_nim/meta/llama-3.1-8b-instruct",
      "nvidia_nim/meta/llama-3.2-11b-vision-instruct",
      "nvidia_nim/meta/llama-3.2-1b-instruct",
      "nvidia_nim/meta/llama-3.2-3b-instruct",
      "nvidia_nim/meta/llama-3.2-90b-vision-instruct",
      "nvidia_nim/meta/llama-3.3-70b-instruct",
      "nvidia_nim/meta/llama-4-maverick-17b-128e-instruct",
      "nvidia_nim/meta/llama-guard-4-12b",
      "nvidia_nim/meta/llama2-70b",
      "nvidia_nim/microsoft/kosmos-2",
      "nvidia_nim/microsoft/phi-3-vision-128k-instruct",
      "nvidia_nim/microsoft/phi-3.5-moe-instruct",
      "nvidia_nim/microsoft/phi-4-mini-instruct",
      "nvidia_nim/microsoft/phi-4-multimodal-instruct",
      "nvidia_nim/minimaxai/minimax-m2.5",
      "nvidia_nim/minimaxai/minimax-m2.7",
      "nvidia_nim/mistralai/codestral-22b-instruct-v0.1",
      "nvidia_nim/mistralai/devstral-2-123b-instruct-2512",
      "nvidia_nim/mistralai/magistral-small-2506",
      "nvidia_nim/mistralai/ministral-14b-instruct-2512",
      "nvidia_nim/mistralai/mistral-7b-instruct-v0.3",
      "nvidia_nim/mistralai/mistral-large",
      "nvidia_nim/mistralai/mistral-large-2-instruct",
      "nvidia_nim/mistralai/mistral-large-3-675b-instruct-2512",
      "nvidia_nim/mistralai/mistral-medium-3-instruct",
      "nvidia_nim/mistralai/mistral-medium-3.5-128b",
      "nvidia_nim/mistralai/mistral-nemotron",
      "nvidia_nim/mistralai/mistral-small-4-119b-2603",
      "nvidia_nim/mistralai/mixtral-8x22b-instruct-v0.1",
      "nvidia_nim/mistralai/mixtral-8x22b-v0.1",
      "nvidia_nim/mistralai/mixtral-8x7b-instruct-v0.1",
      "nvidia_nim/moonshotai/kimi-k2-instruct",
      "nvidia_nim/moonshotai/kimi-k2-instruct-0905",
      "nvidia_nim/moonshotai/kimi-k2-thinking",
      "nvidia_nim/moonshotai/kimi-k2.6",
      "nvidia_nim/nv-mistralai/mistral-nemo-12b-instruct",
      "nvidia_nim/nvidia/ai-synthetic-video-detector",
      "nvidia_nim/nvidia/cosmos-reason2-8b",
      "nvidia_nim/nvidia/gliner-pii",
      "nvidia_nim/nvidia/ising-calibration-1-35b-a3b",
      "nvidia_nim/nvidia/llama-3.1-nemoguard-8b-content-safety",
      "nvidia_nim/nvidia/llama-3.1-nemoguard-8b-topic-control",
      "nvidia_nim/nvidia/llama-3.1-nemotron-51b-instruct",
      "nvidia_nim/nvidia/llama-3.1-nemotron-70b-instruct",
      "nvidia_nim/nvidia/llama-3.1-nemotron-nano-8b-v1",
      "nvidia_nim/nvidia/llama-3.1-nemotron-nano-vl-8b-v1",
      "nvidia_nim/nvidia/llama-3.1-nemotron-safety-guard-8b-v3",
      "nvidia_nim/nvidia/llama-3.1-nemotron-ultra-253b-v1",
      "nvidia_nim/nvidia/llama-3.3-nemotron-super-49b-v1",
      "nvidia_nim/nvidia/llama-3.3-nemotron-super-49b-v1.5",
      "nvidia_nim/nvidia/llama3-chatqa-1.5-70b",
      "nvidia_nim/nvidia/mistral-nemo-minitron-8b-8k-instruct",
      "nvidia_nim/nvidia/nemoretriever-parse",
      "nvidia_nim/nvidia/nemotron-3-content-safety",
      "nvidia_nim/nvidia/nemotron-3-nano-30b-a3b",
      "nvidia_nim/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning",
      "nvidia_nim/nvidia/nemotron-3-super-120b-a12b",
      "nvidia_nim/nvidia/nemotron-4-340b-instruct",
      "nvidia_nim/nvidia/nemotron-4-340b-reward",
      "nvidia_nim/nvidia/nemotron-content-safety-reasoning-4b",
      "nvidia_nim/nvidia/nemotron-mini-4b-instruct",
      "nvidia_nim/nvidia/nemotron-nano-12b-v2-vl",
      "nvidia_nim/nvidia/nemotron-nano-3-30b-a3b",
      "nvidia_nim/nvidia/nemotron-parse",
      "nvidia_nim/nvidia/neva-22b",
      "nvidia_nim/nvidia/nvclip",
      "nvidia_nim/nvidia/nvidia-nemotron-nano-9b-v2",
      "nvidia_nim/nvidia/riva-translate-4b-instruct",
      "nvidia_nim/nvidia/riva-translate-4b-instruct-v1.1",
      "nvidia_nim/nvidia/vila",
      "nvidia_nim/openai/gpt-oss-120b",
      "nvidia_nim/openai/gpt-oss-20b",
      "nvidia_nim/qwen/qwen2.5-coder-32b-instruct",
      "nvidia_nim/qwen/qwen3-coder-480b-a35b-instruct",
      "nvidia_nim/qwen/qwen3-next-80b-a3b-instruct",
      "nvidia_nim/qwen/qwen3-next-80b-a3b-thinking",
      "nvidia_nim/qwen/qwen3.5-122b-a10b",
      "nvidia_nim/qwen/qwen3.5-397b-a17b",
      "nvidia_nim/sarvamai/sarvam-m",
      "nvidia_nim/stepfun-ai/step-3.5-flash",
      "nvidia_nim/stockmark/stockmark-2-100b-instruct",
      "nvidia_nim/upstage/solar-10.7b-instruct",
      "nvidia_nim/writer/palmyra-creative-122b",
      "nvidia_nim/writer/palmyra-fin-70b-32k",
      "nvidia_nim/writer/palmyra-med-70b",
      "nvidia_nim/writer/palmyra-med-70b-32k",
      "nvidia_nim/z-ai/glm-5.1",
      "nvidia_nim/z-ai/glm4.7",
      "nvidia_nim/z-ai/glm5",
      "nvidia_nim/zyphra/zamba2-7b-instruct",
    ],
  },
]

export const EMPTY_PROVIDER: LlmProvider = { id: "", name: "", api_key: "", models: [] }
