import { useEffect, useState } from "react"
import { CockpitButton } from "./CockpitButton"
import { CockpitSectionLabel } from "./CockpitPanel"
import { mediaWorkspaceApi, type MediaScreenplay } from "./mediaWorkspaceApi"

const empty: MediaScreenplay = { title: "", logline: "", acts: [] }
const id = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`

export function MediaScreenplayOverlay({ projectId, mediaSlug, onClose }: { projectId: string; mediaSlug: string; onClose: () => void }) {
  const [value, setValue] = useState<MediaScreenplay>(empty)
  const [message, setMessage] = useState("Lädt…")
  useEffect(() => { mediaWorkspaceApi.getScreenplay(projectId, mediaSlug).then((data) => { setValue(data); setMessage("Regie geladen") }).catch(() => setMessage("Regie nicht erreichbar")) }, [projectId, mediaSlug])
  const save = async () => { try { setValue(await mediaWorkspaceApi.saveScreenplay(projectId, mediaSlug, value)); setMessage("Gespeichert") } catch { setMessage("Speichern fehlgeschlagen") } }
  const updateAct = (ai: number, title: string) => setValue((old) => ({ ...old, acts: old.acts.map((act, index) => index === ai ? { ...act, title } : act) }))

  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/80 p-4" role="dialog" aria-modal="true" aria-labelledby="screenplay-title">
    <section className="flex h-[min(820px,94dvh)] w-full max-w-6xl flex-col overflow-hidden rounded-[4px] border border-[#46617f] bg-[#151c2b]">
      <header className="flex items-center justify-between border-b border-[#2a364b] p-4"><div><CockpitSectionLabel>Regie</CockpitSectionLabel><h2 id="screenplay-title" className="text-lg font-semibold text-[#e8eef8]">Akt → Szene → Shot</h2></div><div className="flex gap-2"><CockpitButton onClick={onClose}>Schließen</CockpitButton><CockpitButton tone="primary" onClick={save}>Speichern</CockpitButton></div></header>
      <div className="grid gap-3 border-b border-[#2a364b] p-4 md:grid-cols-2"><label className="text-xs text-[#8d9ab0]">Filmtitel<input value={value.title} onChange={(e) => setValue({ ...value, title: e.target.value })} className="mt-1 w-full rounded-[4px] border border-[#2a364b] bg-[#0d1420] p-2 text-[#e8eef8]" /></label><label className="text-xs text-[#8d9ab0]">Logline<input value={value.logline} onChange={(e) => setValue({ ...value, logline: e.target.value })} className="mt-1 w-full rounded-[4px] border border-[#2a364b] bg-[#0d1420] p-2 text-[#e8eef8]" /></label></div>
      <main className="min-h-0 flex-1 overflow-y-auto p-4"><div className="space-y-4">{value.acts.map((act, ai) => <section key={act.id} className="rounded-[4px] border border-[#2a364b] bg-[#101724] p-3"><div className="flex gap-2"><input value={act.title} onChange={(e) => updateAct(ai, e.target.value)} className="min-w-0 flex-1 bg-transparent font-semibold text-[#e8eef8] outline-none" /><CockpitButton onClick={() => setValue((old) => ({ ...old, acts: old.acts.filter((_, index) => index !== ai) }))}>Akt löschen</CockpitButton><CockpitButton onClick={() => setValue((old) => ({ ...old, acts: old.acts.map((a, index) => index === ai ? { ...a, scenes: [...a.scenes, { id: id("scene"), title: "Neue Szene", description: "", shots: [] }] } : a) }))}>Szene +</CockpitButton></div><div className="mt-3 space-y-3">{act.scenes.map((scene, si) => <article key={scene.id} className="rounded-[4px] border border-[#2a364b] bg-[#0d1420] p-3"><input value={scene.title} onChange={(e) => setValue((old) => ({ ...old, acts: old.acts.map((a, x) => x === ai ? { ...a, scenes: a.scenes.map((s, y) => y === si ? { ...s, title: e.target.value } : s) } : a) }))} className="w-full bg-transparent text-sm font-semibold text-[#e8eef8] outline-none" /><textarea value={scene.description} onChange={(e) => setValue((old) => ({ ...old, acts: old.acts.map((a, x) => x === ai ? { ...a, scenes: a.scenes.map((s, y) => y === si ? { ...s, description: e.target.value } : s) } : a) }))} placeholder="Szenenbeschreibung" className="mt-2 w-full rounded-[3px] border border-[#2a364b] bg-[#111827] p-2 text-xs text-[#d7deea]" /><div className="mt-2 flex justify-end"><CockpitButton onClick={() => setValue((old) => ({ ...old, acts: old.acts.map((a, x) => x === ai ? { ...a, scenes: a.scenes.map((s, y) => y === si ? { ...s, shots: [...s.shots, { id: id("shot"), title: "Neuer Shot", description: "", duration: 5, camera: "", character_ids: [], asset_ids: [], dialogue: "" }] } : s) } : a) }))}>Shot +</CockpitButton></div><div className="mt-2 grid gap-2 md:grid-cols-2">{scene.shots.map((shot, hi) => <div key={shot.id} className="rounded-[3px] border border-[#2a364b] bg-[#151c2b] p-2"><input value={shot.title} onChange={(e) => setValue((old) => ({ ...old, acts: old.acts.map((a, x) => x === ai ? { ...a, scenes: a.scenes.map((s, y) => y === si ? { ...s, shots: s.shots.map((h, z) => z === hi ? { ...h, title: e.target.value } : h) } : s) } : a) }))} className="w-full bg-transparent text-sm text-[#e8eef8] outline-none" /><p className="mt-1 text-[10px] text-[#8d9ab0]">{shot.duration}s · {shot.camera || "Kamera offen"}</p></div>)}</div></article>)}</div></section>)}</div><CockpitButton onClick={() => setValue((old) => ({ ...old, acts: [...old.acts, { id: id("act"), title: `Akt ${old.acts.length + 1}`, scenes: [] }] }))} className="mt-4">Akt hinzufügen</CockpitButton></main>
      <footer className="border-t border-[#2a364b] p-3 text-xs text-[#8d9ab0]">{message} · Keine Generierung wird durch Speichern gestartet.</footer>
    </section>
  </div>
}
