import { MemberManager } from "@/features/projects/MemberManager"
import { SpecialistsTab } from "@/features/projects/_SpecialistsTab"
import type { Project } from "@/features/projects/types"
import { CockpitButton } from "../CockpitButton"
import { CockpitSectionLabel } from "../CockpitPanel"

export function ProjectAccessOverlay({ project, onClose, onChanged }: { project: Project; onClose: () => void; onChanged: (project: Project) => void }) {
  return <div className="fixed inset-0 z-[100] grid place-items-center bg-black/80 p-4" role="dialog" aria-modal="true" aria-labelledby="project-access-title"><section className="flex h-[min(760px,94dvh)] w-full max-w-4xl flex-col overflow-hidden rounded-[6px] border border-[#46617f] bg-[#151c2b] shadow-2xl"><header className="flex items-center justify-between border-b border-[#2a364b] p-4"><div><CockpitSectionLabel>Zugriff & AgentLink</CockpitSectionLabel><h2 id="project-access-title" className="mt-1 text-lg font-semibold text-[#e8eef8]">Mitglieder und Spezialisten</h2><p className="mt-1 text-xs text-[#8d9ab0]">{project.name}</p></div><CockpitButton onClick={onClose}>Schließen</CockpitButton></header><main className="grid min-h-0 flex-1 gap-4 overflow-y-auto p-4 md:grid-cols-2"><section className="rounded-[4px] border border-[#2a364b] bg-[#101724] p-4"><h3 className="mb-3 text-sm font-semibold text-[#e8eef8]">Projektmitglieder</h3><p className="mb-4 text-xs leading-5 text-[#8d9ab0]">Mitglieder erhalten Zugriff auf Projekt, Workspace und projektgebundene Funktionen.</p><MemberManager project={project} onChange={onChanged} /></section><section className="rounded-[4px] border border-[#2a364b] bg-[#101724] p-4"><h3 className="mb-3 text-sm font-semibold text-[#e8eef8]">Freigegebene Spezialisten</h3><SpecialistsTab project={project} onSaved={onChanged} /></section></main><footer className="border-t border-[#2a364b] p-3 text-xs text-[#8d9ab0]">Mitgliederänderungen werden über die bestehende Projekt-API auditierbar ausgeführt.</footer></section></div>
}
